let actionList = [
    {
        index:1,
        name:'add_user',
        icon:'plus-outline',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
    {
        index:2,
        name:'edit',
        icon:'pencil',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
    
    {
        index:3,
        name:'save',
        icon:'save',
        type:'action',
        isDisabled:true,
        isHidden:false
    },
    {
        index:4,
        name:'delete',
        icon:'trash',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
    {
        index:5,
        name:'cancel',
        icon:'x',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
    {
        index:6,
        name:'import',
        icon:'import',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
    {
        index:7,
        name:'export',
        icon:'export',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
    {
        index:8,
        name:'excel',
        icon:'file-excel',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
    {
        index:9,
        name:'pdf',
        icon:'file-pdf',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
    {
        index:10,
        name:'word',
        icon:'file-word',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
    {
        index:11,
        name:'upload',
        icon:'upload',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
    {
        index:12,
        name:'download',
        icon:'download',
        type:'action',
        isDisabled:false,
        isHidden:false
    },
]

export default actionList;